# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Role
metadata:
  name: endpoint-viewer
rules:
- apiGroups: null
  attributeRestrictions: null
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
